; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "EKTOpt"
#define MyAppVersion "3.0"
#define MyAppPublisher "IIT Bombay"
#define MyAppURL "https://www.coeoge.iitb.ac.in/"
#define MyAppExeName "EKTOpt.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{823495BE-7F6D-4876-B36C-5070061E1991}
AppName={#MyAppName}_v{#MyAppVersion}
AppVersion={#MyAppVersion}
AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}_v{#MyAppVersion}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
LicenseFile=C:\Users\Siddhesh\Documents\pipeline-estimation\app\dist\license.txt
; Remove the following line to run in administrative install mode (install for all users.)
PrivilegesRequired=lowest
OutputDir=C:\Users\Siddhesh\Documents\pipeline-estimation\app\setup_v{#MyAppVersion}
OutputBaseFilename=EKTOpt_WINDOWS_64_{#MyAppVersion}_setup
SetupIconFile=C:\Users\Siddhesh\Downloads\Gemini_Generated_Image_oyta00oyta00oyta.ico
Password=IOCL_IITB_EKTOpt@{#MyAppVersion}
Encryption=yes
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\Siddhesh\Documents\pipeline-estimation\app\dist\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Siddhesh\Documents\pipeline-estimation\app\dist\icon\*"; DestDir: "{app}/icon"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\Siddhesh\Documents\pipeline-estimation\app\dist\img\*"; DestDir: "{app}/img"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\Siddhesh\Documents\pipeline-estimation\app\dist\logs\*"; DestDir: "{app}/logs"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\Siddhesh\Documents\pipeline-estimation\app\dist\MATLAB\OUTPUT\*"; DestDir: "{app}/MATLAB/OUTPUT"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\Siddhesh\Documents\pipeline-estimation\app\dist\MATLAB\CSV_OUTPUT\*"; DestDir: "{app}/MATLAB/CSV_OUTPUT"; Flags: ignoreversion recursesubdirs createallsubdirs

; License file
Source: "C:\Users\Siddhesh\Documents\pipeline-estimation\app\dist\license.txt"; DestDir: "{app}"; Flags: ignoreversion

; NOTE: Don't use "Flags: ignoreversion" on any shared system filess

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[UninstallDelete]
Type: filesandordirs; Name: "{app}\logs\*"
Type: filesandordirs; Name: "{app}\MATLAB\OUTPUT\*"
Type: filesandordirs; Name: "{app}\MATLAB\CSV_OUTPUT\*"
Type: filesandordirs; Name: "{app}\logs"
Type: filesandordirs; Name: "{app}\MATLAB"

